#!/usr/bin/env bash
set -euo pipefail

NOTICE='Generated by ChatGPT, Reviewed by a Human'

# ---------- Helpers ----------
log()  { echo -e "\n[quickarr] $*"; }
warn() { echo -e "\n[quickarr][WARN] $*" >&2; }
die()  { echo -e "\n[quickarr][ERROR] $*" >&2; exit 1; }

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    die "Run this script as root (use: sudo $0)"
  fi
}

prompt_default() {
  local prompt="$1"; local default="$2"; local var
  read -r -p "$prompt [$default]: " var || true
  if [[ -z "${var}" ]]; then
    echo "$default"
  else
    echo "$var"
  fi
}

# Preflight: ensure APT isn't broken by Docker Signed-By conflicts and stray backup files
preflight_fix_docker_apt_conflict() {
  local ts; ts="$(date +%Y%m%d_%H%M%S)"
  local backup_dir="/root/quickarr-apt-backups/${ts}"
  mkdir -p "$backup_dir"

  # 1) Remove any Docker repo lines from /etc/apt/sources.list (if present)
  if grep -qs "download\.docker\.com/linux/ubuntu" /etc/apt/sources.list 2>/dev/null; then
    warn "Preflight: Docker repo found in /etc/apt/sources.list. Backing up + removing those lines..."
    cp -a /etc/apt/sources.list "${backup_dir}/sources.list"
    # Delete docker repo lines completely (safer than commenting, avoids Signed-By conflicts)
    sed -i '/download\.docker\.com\/linux\/ubuntu/d' /etc/apt/sources.list
  fi

  # 2) Move aside ANY file in sources.list.d that references Docker, regardless of extension
  shopt -s nullglob
  for f in /etc/apt/sources.list.d/*; do
    if grep -qs "download\.docker\.com/linux/ubuntu" "$f" 2>/dev/null; then
      warn "Preflight: Moving docker repo file out of APT: $f"
      mv "$f" "${backup_dir}/$(basename "$f")"
    fi
  done
  shopt -u nullglob

  # 3) Remove docker key variants to avoid Signed-By mismatch; we will recreate docker.gpg later
  if [[ -f /etc/apt/keyrings/docker.asc || -f /etc/apt/keyrings/docker.gpg ]]; then
    warn "Preflight: Removing existing Docker key files (docker.asc/docker.gpg) so we can recreate cleanly..."
    rm -f /etc/apt/keyrings/docker.asc /etc/apt/keyrings/docker.gpg
  fi
}

# ---------- Banner ----------
require_root
echo "==============================================="
echo " quickarr - Ubuntu 24.04.3 media stack installer"
echo " $NOTICE"
echo "==============================================="

log "This will install Docker + Samba, configure an SMB share, and deploy Radarr/Sonarr/Prowlarr/Jellyfin/Jellyseerr."
log "If you're allergic to scripts touching your system, press Ctrl+C now. Otherwise... onward."

# ---------- PRE-FLIGHT (MUST be before any apt-get update) ----------
preflight_fix_docker_apt_conflict

# ---------- Collect inputs ----------
DEFAULT_SHARE_PATH="/srv/samba/quickarr"
DEFAULT_SHARE_NAME="QuickARR"

SHARE_PATH="$(prompt_default 'SMB share path (will be created if missing)' "$DEFAULT_SHARE_PATH")"
SHARE_NAME="$(prompt_default 'SMB share name' "$DEFAULT_SHARE_NAME")"

DEFAULT_OWNER_USER="${SUDO_USER:-$(logname 2>/dev/null || echo "ubuntu")}"
OWNER_USER="$(prompt_default 'Linux user to own media/config files (must already exist)' "$DEFAULT_OWNER_USER")"
if ! id "$OWNER_USER" >/dev/null 2>&1; then
  die "User '$OWNER_USER' does not exist. Create it first (e.g., sudo adduser $OWNER_USER), then re-run."
fi

SMB_USER="$(prompt_default 'Samba username to access the share (must be an existing Linux user)' "$OWNER_USER")"
if ! id "$SMB_USER" >/dev/null 2>&1; then
  die "User '$SMB_USER' does not exist. Create it first, then re-run."
fi

ALLOWED_SUBNET="$(prompt_default 'Optional: restrict SMB access to subnet/CIDR (blank for no restriction)' "")"

TZ_VALUE="$(cat /etc/timezone 2>/dev/null || echo "Etc/UTC")"
TZ_VALUE="$(prompt_default 'Timezone for containers (TZ database name)' "$TZ_VALUE")"

PUID="$(id -u "$OWNER_USER")"
PGID="$(id -g "$OWNER_USER")"

# ---------- Install pa
