#!/usr/bin/env bash
set -euo pipefail

NOTICE='Generated by ChatGPT, Reviewed by a Human'

# ---------- Helpers ----------
log()  { echo -e "\n[quickarr] $*"; }
warn() { echo -e "\n[quickarr][WARN] $*" >&2; }
die()  { echo -e "\n[quickarr][ERROR] $*" >&2; exit 1; }

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    die "Run this script as root (use: sudo $0)"
  fi
}

prompt_default() {
  local prompt="$1"; local default="$2"; local var
  read -r -p "$prompt [$default]: " var || true
  if [[ -z "${var}" ]]; then
    echo "$default"
  else
    echo "$var"
  fi
}

validate_share_path() {
  local input="$1"
  [[ -n "$input" ]] || die "SMB share path cannot be empty."

  # Normalize path (tolerates non-existent segments)
  local p
  p="$(realpath -m -- "$input")" || die "Invalid SMB share path: $input"

  # Must be absolute
  [[ "$p" == /* ]] || die "SMB share path must be an absolute path (starts with /). Got: $p"

  # Absolutely never allow root
  [[ "$p" != "/" ]] || die "SMB share path cannot be '/'. Use something like /srv/samba/quickarr or /mnt/media/quickarr."

  # Block pseudo/system mountpoints and OS dirs
  case "$p" in
    /proc|/proc/*|/sys|/sys/*|/dev|/dev/*|/run|/run/*|/boot|/boot/*)
      die "SMB share path cannot be inside system/pseudo filesystems (proc/sys/dev/run/boot). Got: $p"
      ;;
    /etc|/etc/*|/bin|/bin/*|/sbin|/sbin/*|/lib|/lib/*|/lib64|/lib64/*|/usr|/usr/*)
      die "SMB share path cannot be inside OS directories (/etc,/usr,/bin,/lib,...). Got: $p"
      ;;
  esac

  # Optional: enforce “safe roots” only (uncomment if you want to be strict)
  # case "$p" in
  #   /srv/*|/mnt/*|/media/*|/opt/*) ;;
  #   *) die "SMB share path must live under /srv, /mnt, /media, or /opt. Got: $p" ;;
  # esac

  echo "$p"
}

validate_share_name() {
  local name="$1"
  [[ -n "$name" ]] || die "SMB share name cannot be empty."
  [[ "$name" =~ ^[A-Za-z0-9._-]+$ ]] || die "SMB share name must be alnum plus . _ - (no spaces). Got: '$name'"
}

safe_chown_tree() {
  local owner_user="$1"; local owner_group="$2"; shift 2
  local targets=("$@")
  for t in "${targets[@]}"; do
    [[ -d "$t" ]] || continue
    chown -R "${owner_user}:${owner_group}" "$t"
  done
}

# Preflight: ensure APT isn't broken by Docker Signed-By conflicts and stray backup files
preflight_fix_docker_apt_conflict() {
  local ts; ts="$(date +%Y%m%d_%H%M%S)"
  local backup_dir="/root/quickarr-apt-backups/${ts}"
  mkdir -p "$backup_dir"

  # 1) Remove any Docker repo lines from /etc/apt/sources.list (if present)
  if grep -qs "download\.docker\.com/linux/ubuntu" /etc/apt/sources.list 2>/dev/null; then
    warn "Preflight: Docker repo found in /etc/apt/sources.list. Backing up + removing those lines..."
    cp -a /etc/apt/sources.list "${backup_dir}/sources.list"
    # Delete docker repo lines completely (safer than commenting, avoids Signed-By conflicts)
    sed -i '/download\.docker\.com\/linux\/ubuntu/d' /etc/apt/sources.list
  fi

  # 2) Move aside ANY file in sources.list.d that references Docker, regardless of extension
  shopt -s nullglob
  for f in /etc/apt/sources.list.d/*; do
    if grep -qs "download\.docker\.com/linux/ubuntu" "$f" 2>/dev/null; then
      warn "Preflight: Moving docker repo file out of APT: $f"
      mv "$f" "${backup_dir}/$(basename "$f")"
    fi
  done
  shopt -u nullglob

  # 3) Remove docker key variants to avoid Signed-By mismatch; we will recreate docker.gpg later
  if [[ -f /etc/apt/keyrings/docker.asc || -f /etc/apt/keyrings/docker.gpg ]]; then
    warn "Preflight: Removing existing Docker key files (docker.asc/docker.gpg) so we can recreate cleanly..."
    rm -f /etc/apt/keyrings/docker.asc /etc/apt/keyrings/docker.gpg
  fi
}

# ---------- Banner ----------
require_root
echo "==============================================="
echo " quickarr - Ubuntu 24.04.3 media stack installer"
echo " $NOTICE"
echo "==============================================="

log "This will install Docker + Samba, configure an SMB share, and deploy Radarr/Sonarr/Prowlarr/Jellyfin/Jellyseerr."

# ---------- PRE-FLIGHT (MUST be before any apt-get update) ----------
preflight_fix_docker_apt_conflict

# ---------- Collect inputs ----------
DEFAULT_SHARE_PATH="/srv/samba/quickarr"
DEFAULT_SHARE_NAME="QuickARR"

SHARE_PATH="$(prompt_default 'SMB share path (will be created if missing)' "$DEFAULT_SHARE_PATH")"
SHARE_PATH="$(validate_share_path "$SHARE_PATH")"

SHARE_NAME="$(prompt_default 'SMB share name' "$DEFAULT_SHARE_NAME")"
validate_share_name "$SHARE_NAME"

DEFAULT_OWNER_USER="${SUDO_USER:-$(logname 2>/dev/null || echo "ubuntu")}"
OWNER_USER="$(prompt_default 'Linux user to own media/config files (must already exist)' "$DEFAULT_OWNER_USER")"
if ! id "$OWNER_USER" >/dev/null 2>&1; then
  die "User '$OWNER_USER' does not exist. Create it first (e.g., sudo adduser $OWNER_USER), then re-run."
fi

SMB_USER="$(prompt_default 'Samba username to access the share (must be an existing Linux user)' "$OWNER_USER")"
if ! id "$SMB_USER" >/dev/null 2>&1; then
  die "User '$SMB_USER' does not exist. Create it first, then re-run."
fi

ALLOWED_SUBNET="$(prompt_default 'Optional: restrict SMB access to subnet/CIDR (blank for no restriction)' "")"

TZ_VALUE="$(cat /etc/timezone 2>/dev/null || echo "Etc/UTC")"
TZ_VALUE="$(prompt_default 'Timezone for containers (TZ database name)' "$TZ_VALUE")"

PUID="$(id -u "$OWNER_USER")"
PGID="$(id -g "$OWNER_USER")"

# ---------- Install packages ----------
log "Updating apt + installing prerequisites..."
apt-get update -y
apt-get install -y ca-certificates curl gnupg lsb-release apt-transport-https software-properties-common

# ---------- Install Docker Engine (official repo method) ----------
log "Installing Docker Engine + docker compose plugin..."

# Remove conflicting packages if present (best-effort)
for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do
  if dpkg -s "$pkg" >/dev/null 2>&1; then
    warn "Removing conflicting package: $pkg"
    apt-get remove -y "$pkg" || true
  fi
done

# Ensure keyrings dir exists
install -m 0755 -d /etc/apt/keyrings

# Recreate docker.gpg NON-INTERACTIVELY (no prompts)
curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
  | gpg --dearmor --batch --yes -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

UBUNTU_CODENAME="$(. /etc/os-release && echo "${VERSION_CODENAME}")"
ARCH="$(dpkg --print-architecture)"

cat >/etc/apt/sources.list.d/docker.list <<EOF
deb [arch=${ARCH} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu ${UBUNTU_CODENAME} stable
EOF

apt-get update -y
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
systemctl enable --now docker

# Add OWNER_USER to docker group (so they can run docker without sudo)
if ! getent group docker >/dev/null; then
  groupadd docker || true
fi
usermod -aG docker "$OWNER_USER" || true
log "Docker installed. Note: '$OWNER_USER' may need to log out/in for docker group changes to apply."

# ---------- Install Samba ----------
log "Installing Samba..."
apt-get install -y samba samba-common-bin
systemctl enable --now smbd nmbd || systemctl enable --now smbd || true

# ---------- Configure SMB share ----------
log "Creating share folder structure..."
mkdir -p \
  "$SHARE_PATH/media/Movies" \
  "$SHARE_PATH/media/Music" \
  "$SHARE_PATH/media/Shows" \
  "$SHARE_PATH/downloads"

# IMPORTANT: never chown the base path itself (prevents SHARE_PATH=/ disaster)
safe_chown_tree "$OWNER_USER" "$OWNER_USER" \
  "$SHARE_PATH/media" \
  "$SHARE_PATH/downloads"

# Permissions: setgid so new files inherit group
chmod -R 2775 "$SHARE_PATH/media" "$SHARE_PATH/downloads"

log "Configuring Samba share in /etc/samba/smb.conf (with a backup)..."
SMB_CONF="/etc/samba/smb.conf"
cp -a "$SMB_CONF" "${SMB_CONF}.bak.$(date +%Y%m%d_%H%M%S)"

if grep -q "^\[$SHARE_NAME\]" "$SMB_CONF"; then
  warn "Share [$SHARE_NAME] already exists in smb.conf. Skipping stanza append."
else
  {
    echo ""
    echo "[$SHARE_NAME]"
    echo "   path = $SHARE_PATH"
    echo "   browseable = yes"
    echo "   read only = no"
    echo "   guest ok = no"
    echo "   create mask = 0664"
    echo "   directory mask = 2775"
    echo "   force user = $OWNER_USER"
    echo "   force group = $OWNER_USER"
    echo "   vfs objects = fruit streams_xattr"
    echo "   fruit:metadata = stream"
    echo "   fruit:model = MacSamba"
    echo "   fruit:posix_rename = yes"
    echo "   fruit:veto_appledouble = no"
    echo "   fruit:wipe_intentionally_left_blank_rfork = yes"
    echo "   fruit:delete_empty_adfiles = yes"
    if [[ -n "$ALLOWED_SUBNET" ]]; then
      echo "   hosts allow = $ALLOWED_SUBNET"
      echo "   hosts deny = 0.0.0.0/0"
    fi
  } >> "$SMB_CONF"
fi

log "Setting Samba password for user '$SMB_USER'..."
smbpasswd -a "$SMB_USER"

log "Restarting Samba..."
systemctl restart smbd || true
systemctl restart nmbd || true

# ---------- Docker Compose stack ----------
STACK_DIR="/opt/quickarr"
CONFIG_DIR="${STACK_DIR}/config"
mkdir -p "$CONFIG_DIR"/{radarr,sonarr,prowlarr,jellyfin,jellyseerr}

chown -R "$OWNER_USER":"$OWNER_USER" "$STACK_DIR"
chmod -R 2775 "$STACK_DIR"

log "Writing docker compose stack to $STACK_DIR/compose.yaml ..."
cat > "${STACK_DIR}/compose.yaml" <<EOF
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ_VALUE}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ_VALUE}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${SHARE_PATH}/media/Movies:/movies
      - ${SHARE_PATH}/downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
    depends_on:
      - prowlarr

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ_VALUE}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${SHARE_PATH}/media/Shows:/tv
      - ${SHARE_PATH}/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
    depends_on:
      - prowlarr

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ_VALUE}
    volumes:
      - ${CONFIG_DIR}/jellyfin:/config
      - ${SHARE_PATH}/media:/media
    ports:
      - "8096:8096"
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=${TZ_VALUE}
    volumes:
      - ${CONFIG_DIR}/jellyseerr:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped
    depends_on:
      - jellyfin
EOF

log "Starting containers..."
cd "$STACK_DIR"
docker compose up -d

# ---------- Final info ----------
IP_ADDR="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
log "Done. Services should be reachable at:"
echo "  - Prowlarr   : http://${IP_ADDR:-<server-ip>}:9696"
echo "  - Radarr     : http://${IP_ADDR:-<server-ip>}:7878"
echo "  - Sonarr     : http://${IP_ADDR:-<server-ip>}:8989"
echo "  - Jellyfin   : http://${IP_ADDR:-<server-ip>}:8096"
echo "  - Jellyseerr : http://${IP_ADDR:-<server-ip>}:5055"
echo ""
log "SMB Share:"
echo "  - Share name : ${SHARE_NAME}"
echo "  - Path       : ${SHARE_PATH}"
echo "  - Example    : \\\\${IP_ADDR:-<server-ip>}\\${SHARE_NAME}"
echo ""
warn "Heads-up:"
echo "  - Consider installing qbittorrent-nox and using a VPN provider for torrent traffic."
echo "  - You created a ${SHARE_PATH}/downloads folder so you can wire a download client into Radarr/Sonarr later."
echo ""
log "If something breaks, the Samba config backup is at: ${SMB_CONF}.bak.*"
log "Enjoy your new media stack. Stop the killing, stop the dying. God bless!."
