#!/usr/bin/env bash
set -euo pipefail

# -----------------------------
# Media Server Bootstrap Script
# Ubuntu Server 24.04 (Noble X)
# Generated by ChatGPT, Reviewed by a Human
# -----------------------------

bold() { echo -e "\033[1m$*\033[0m"; }
info() { echo -e "• $*"; }
warn() { echo -e "\033[33m! $*\033[0m"; }
err()  { echo -e "\033[31m✗ $*\033[0m" >&2; }
ok()   { echo -e "\033[32m✓ $*\033[0m"; }

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    err "Run this as root (use: sudo bash $0)"
    exit 1
  fi
}

check_os() {
  if [[ -r /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    if [[ "${ID:-}" != "ubuntu" ]]; then
      warn "This script was made for Ubuntu. Detected: ${ID:-unknown}. Continuing anyway."
    fi
    if [[ "${VERSION_ID:-}" != "24.04.03" ]]; then
      warn "This script targets Ubuntu 24.04.3 Detected: ${VERSION_ID:-unknown}. Continuing anyway."
    fi
  fi
}

apt_prep() {
  info "Updating apt + installing prerequisites..."
  apt-get update -y
  apt-get install -y ca-certificates curl gnupg lsb-release apt-transport-https software-properties-common
  ok "APT prerequisites installed."
}

install_docker() {
  bold "Installing Docker Engine + Compose plugin"
  info "Removing potentially conflicting packages (if present)..."
  apt-get remove -y docker.io docker-compose docker-compose-v2 docker-doc podman-docker containerd runc >/dev/null 2>&1 || true

  info "Adding Docker official apt repo + GPG key..."
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc

  local codename
  codename="$(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")"
  cat > /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: ${codename}
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF

  apt-get update -y
  info "Installing Docker packages..."
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  systemctl enable --now docker
  ok "Docker installed and service started."

  # Add the invoking user to docker group (so they can run docker without sudo)
  if [[ -n "${SUDO_USER:-}" && "${SUDO_USER}" != "root" ]]; then
    info "Adding ${SUDO_USER} to the docker group..."
    usermod -aG docker "${SUDO_USER}" || true
    warn "You may need to log out/in for docker group changes to apply."
  fi
}

install_samba() {
  bold "Installing Samba"
  apt-get install -y samba samba-common-bin
  systemctl enable --now smbd nmbd || systemctl enable --now smbd || true
  ok "Samba installed and started."
}

prompt() {
  local var_name="$1"
  local text="$2"
  local default="${3:-}"
  local secret="${4:-false}"

  local input=""
  if [[ "${secret}" == "true" ]]; then
    read -r -s -p "${text} [${default}]: " input
    echo
  else
    read -r -p "${text} [${default}]: " input
  fi
  input="${input:-$default}"
  printf -v "${var_name}" '%s' "${input}"
}

setup_smb_share() {
  bold "SMB Share Setup (interactive)"
  prompt SHARE_NAME "Share name" "media-share"
  prompt SHARE_PATH "Share path (will be created if missing)" "/srv/samba/${SHARE_NAME}"
  prompt SMB_USER "Linux user to own/share files (will be created if missing)" "${SUDO_USER:-media}"

  prompt ALLOW_GUEST "Allow guest access? (yes/no)" "no"

  # Create group 'media' for sane permissions across apps/users
  if ! getent group media >/dev/null; then
    info "Creating group: media"
    groupadd media
  fi

  # Create user if missing
  if ! id "${SMB_USER}" >/dev/null 2>&1; then
    info "Creating user: ${SMB_USER}"
    adduser --disabled-password --gecos "" "${SMB_USER}"
  fi

  # Ensure user is in 'media' group
  usermod -aG media "${SMB_USER}" || true
  if [[ -n "${SUDO_USER:-}" && "${SUDO_USER}" != "root" ]]; then
    usermod -aG media "${SUDO_USER}" || true
  fi

  info "Creating share folders..."
  mkdir -p "${SHARE_PATH}/media/Movies" "${SHARE_PATH}/media/Music" "${SHARE_PATH}/media/Shows"

  # Ownership + permissions:
  # - group media
  # - setgid bit so new files inherit group
  chown -R "${SMB_USER}:media" "${SHARE_PATH}"
  chmod -R 2775 "${SHARE_PATH}"
  find "${SHARE_PATH}" -type f -exec chmod 0664 {} \; || true

  ok "Folders created:"
  info "  ${SHARE_PATH}/media/Movies"
  info "  ${SHARE_PATH}/media/Music"
  info "  ${SHARE_PATH}/media/Shows"

  # Samba password for the user (skip if guest)
  if [[ "${ALLOW_GUEST}" != "yes" ]]; then
    bold "Set Samba password for ${SMB_USER}"
    info "You'll be prompted for a Samba password now."
    smbpasswd -a "${SMB_USER}"
    smbpasswd -e "${SMB_USER}"
  else
    warn "Guest access enabled. Anyone on your network can access this share. (You have been warned.)"
  fi

  # Backup smb.conf
  local backup="/etc/samba/smb.conf.backup.$(date +%Y%m%d-%H%M%S)"
  cp -a /etc/samba/smb.conf "${backup}"
  ok "Backed up smb.conf to: ${backup}"

  # Remove old block if re-running
  sed -i "/# BEGIN ${SHARE_NAME}/,/# END ${SHARE_NAME}/d" /etc/samba/smb.conf

  info "Writing share definition to smb.conf..."
  {
    echo ""
    echo "# BEGIN ${SHARE_NAME}"
    echo "[${SHARE_NAME}]"
    echo "   path = ${SHARE_PATH}"
    echo "   browseable = yes"
    echo "   read only = no"
    echo "   create mask = 0664"
    echo "   directory mask = 2775"
    echo "   force group = media"
    echo "   inherit permissions = yes"
    if [[ "${ALLOW_GUEST}" == "yes" ]]; then
      echo "   guest ok = yes"
    else
      echo "   guest ok = no"
      echo "   valid users = ${SMB_USER} @media"
    fi
    echo "# END ${SHARE_NAME}"
  } >> /etc/samba/smb.conf

  info "Validating Samba config (testparm)..."
  testparm -s >/dev/null
  ok "Samba config looks valid."

  systemctl restart smbd nmbd || systemctl restart smbd
  ok "Samba restarted."

  bold "SMB Share Ready"
  info "Windows path: \\\\$(hostname -I | awk '{print $1}')\\${SHARE_NAME}"
  info "Linux mount example: sudo mount -t cifs //SERVER_IP/${SHARE_NAME} /mnt/${SHARE_NAME} -o username=${SMB_USER}"
}

install_servarr() {
  bold "Installing Servarr apps (interactive script)"
  warn "This step is interactive. You'll choose which app(s) to install."
  warn "Tip: Run it multiple times if you want multiple apps (Radarr/Prowlarr/Lidarr/etc.)."

  local tmp="/tmp/servarr-install-script.sh"
  info "Downloading Servarr community install script..."
  curl -fsSL "https://raw.githubusercontent.com/Servarr/Wiki/master/servarr/servarr-install-script.sh" -o "${tmp}"
  chmod +x "${tmp}"

  info "Running Servarr installer..."
  bash "${tmp}"

  ok "Servarr installer finished (for the app you selected)."
}

install_jellyfin() {
  bold "Installing Jellyfin"
  warn "This uses Jellyfin's official Deb/Ubuntu installer script."
  info "Running: curl https://repo.jellyfin.org/install-debuntu.sh | bash"
  curl -fsSL https://repo.jellyfin.org/install-debuntu.sh | bash

  systemctl enable --now jellyfin
  ok "Jellyfin installed and started."
  info "Jellyfin Web UI: http://$(hostname -I | awk '{print $1}'):8096"
}

install_jellyseerr_compose() {
  bold "Installing Jellyseerr (Docker Compose)"
  local base="/opt/jellyseerr"
  local config="${base}/config"
  local tz="UTC"

  if [[ -r /etc/timezone ]]; then
    tz="$(cat /etc/timezone || true)"
  else
    # fallback to timedatectl parsing
    tz="$(timedatectl show -p Timezone --value 2>/dev/null || echo "UTC")"
  fi

  info "Creating directories in ${base}..."
  mkdir -p "${config}"

  info "Writing compose.yaml..."
  cat > "${base}/compose.yaml" <<EOF
services:
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    init: true
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=${tz}
      - PORT=5055
    ports:
      - "5055:5055"
    volumes:
      - ${config}:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
EOF

  info "Starting Jellyseerr..."
  (cd "${base}" && docker compose up -d)
  ok "Jellyseerr is up."
  info "Jellyseerr Web UI: http://$(hostname -I | awk '{print $1}'):5055"
}

final_notes() {
  echo ""
  bold "Next steps"
  warn "1) If you plan to sail the seas consider installing qbittorrent-nox and using a reputable VPN."
  warn "2) Published container ports can bypass ufw rules if you rely on ufw for security."
  info "3) If you added your user to the docker group, log out/in before running docker without sudo."
  echo ""
  bold "What got installed:"
  info "• Docker Engine + Compose"
  info "• Samba + SMB share + media folders"
  info "• Servarr (interactive installer)"
  info "• Jellyfin (http://SERVER_IP:8096)"
  info "• Jellyseerr (http://SERVER_IP:5055)"
  echo ""
  ok "Done. Stop the killing, stop the dying. God bless!"
}

main() {
  require_root
  check_os
  apt_prep
  install_docker
  install_samba
  setup_smb_share
  install_servarr
  install_jellyfin
  install_jellyseerr_compose
  final_notes
}

main "$@"
